# This Travis-CI file is for testing the functionality of my Makefile.
# It is NOT for testing MOM6.

# This is a not a c-language project but it does use "make"
language: c
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - tcsh pkg-config netcdf-bin libnetcdf-dev openmpi-bin libopenmpi-dev gfortran

# Test critical targets in the Makefile
script:
 # Clone if cache was missing
 - make clone REGRESSIONS_URL=https://github.com/adcroft/Gaea-stats-MOM6-examples.git
 # Test changing to dev branchs
 - make dev_tags
 # Pull latest source code
 - make dev_pull
 # Extract cached build
 - make SITE=linux-ubuntu-trusty BUILD_DIR=build REL_PATH=../../../.. build/gnu/shared/repro/libfms.a
 - make SITE=linux-ubuntu-trusty BUILD_DIR=build REL_PATH=../../../.. build/gnu/ocean_only/repro/MOM6
 # Cache build
 - make SITE=linux-ubuntu-trusty BUILD_DIR=build MPIRUN=mpirun NPES=2 Gaea-stats-MOM6-examples/MOM6-examples/ocean_only/double_gyre/ocean.stats.gnu
